<!--
    Generates the Sign-Up for Doctors pages. List boxes are generated by PHP, as values are passed from the database.
-->
<?php
//Recieves any error message sent from the Doctor Sign-Up script. The error has to be detected on the server side.
    $outputMessage = filter_input(INPUT_GET,'outputMessage');

//Checks whether outputMessage is set, if not creates empty string variable
    if(!empty($outputMessage)){
        $outputMessage = "<p>" . $outputMessage . "</p>";
    }
    else{
        $outputMessage="";
    }

//retieves an associated array of specialization names and their ids to generate the specialization list. 
    require('./database.php');
    $query = 'select * from specialization;';
    $statement = $database->prepare($query);    //Query is prepared as a PDOStatement object and sent to database server.
    $statement->execute();  //executes query in nthe SQL server.
    $specialization_table = $statement->fetchAll(); //Retrieves values as associative array.
    $statement->closeCursor();  //Terminates connection to the SQL server, allowing other statements to be issued. 
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <meta name="author" content="T Lakshan">
        <title>Doctorr | Doctor | Sign-Up</title>

        <!-- Links bootstrap CSS and JavaScript to the HTML document -->
        <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
        <script src="js/bootstrap.min.js"></script>

        <!-- Links custom CSS and JavaScript to HTML document -->
        <link rel="stylesheet" type="text/css" href="formStyle.css">
        <script src="formScript.js"></script>
    </head>
    
    <body>
        <!-- divs used for alignment using both bootstrap classes and custom CSS -->
        <div class="row my-4 align-items-center body-section">
            <div class="col">
            <!-- Creates Heading -->
                <header>
                    <h1 class="text-center">Sign&hybull;Up&nbsp;as&nbsp;a&nbsp;Doctor <img src="images/logo2.png" alt="Doctorr Logo"></h1>
                </header>
                <!-- Aligns the form to center of the page, both vertically and horizontally -->
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col col-lg-5 col-md-6 col-sm-8 col-10">

                        <!-- Creates the Sign Up form -->
                            <form class="container-fluid border rounded-3 pt-5 pb-4 bg-light" action="doctorSignUpScript.php" method="POST">
                            <!--
                                Custom JavaScript functions are used for client side validation.
                            -->

                            <!-- Prints the output message. Custom CSS styles are added -->
                                <div class="error-msg">
                                    <div>
                                        <?php echo $outputMessage?>
                                    </div>
                                </div>
                              
                                <!-- text control for the Doctor Name -->
                                <div class="row mb-2">
                                    <div class="col col-12">
                                        <div class="input-group">
                                            <span class="input-group-text">Dr.</span>
                                            <input type="text" id="uName" name="uName" class="form-control control-height"  placeholder="Name" onchange="strTrimmer(this);" onblur="invalidBorder(this);" required>
                                        </div>
                                    </div>
                                </div>
                              
                                <!-- 
                                    Creates list to select Gender. As only two values present, it is not generated from PHP.
                                    divs with bootstrap classes are used for responsive positioning, sizing and alignment.
                                -->
                                <div class="row mb-2 p-2 control-height align-items-center">
                                    <div class="col col-xl-2 col-sm-3 col-4">
                                        <label for="uGender">Gender</label>
                                    </div>
                                    <div class="col-xl-4 col-sm-5 col-8">
                                        <select id="uGender" name="uGender" class="form-select" onblur="invalidBorder(this);" required>
                                            <option class="select-item" value="" disabled selected></option>
                                            <option class="select-item" value="M">Male</option>
                                            <option class="select-item" value="F">Female</option>
                                        </select>
                                    </div>
                                </div>
                             
                                <!-- text control to input Email -->
                                <div class="row mb-2">
                                    <div class="col">
                                        <div class="form-floating">
                                            <input type="email" id="uEmail" name="uEmail" class="form-control"  placeholder="Your E-mail" onblur="invalidBorder(this);" required>
                                            <label for="uEmail">E-mail</label>
                                        </div>
                                    </div>
                                </div>
                                <!-- text control to input Password -->
                                <div class="row gx-2">
                                    <div class="col-xl-6 col-12">
                                        <div class="form-floating mb-2">
                                            <input type="password" id="uPassword" name="uPassword" class="form-control"  minlength="8" placeholder="Your Password" onblur="invalidBorder(this);" required>
                                            <label for="uPassword">Password</label>
                                        </div>
                                    </div>
                                <!-- text control to re-enter Password -->
                                    <div class="col-xl-6 col-12">
                                        <div class="form-floating mb-2">
                                            <input type="password" id="uPassRepeat" name="uPassRepeat" class="form-control"  placeholder="Re-enter Your Password" onblur="invalidBorder(this);" oninput="clearInvalid(this);" required>
                                            <label for="uPassRepeat">Re-enter Password</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="row gx-2">
                                <!-- Generates the Specialization list from the associative array -->
                                    <div class="col">
                                        <select id="doctorSpec" name="doctorSpec" class="form-select control-height mb-2" onblur="invalidBorder(this);" required>
                                            <option class="select-item" value="" disabled selected>Select Your Specialization</option>
                                            <?php foreach($specialization_table as $specialization_record):?>
                                                <option class="select-item" value="<?php echo $specialization_record['specialization_id']?>"><?php echo $specialization_record['specialization_name']?></option>
                                            <?php endforeach?>
                                        </select>
                                    </div>
                                </div>
                                <!-- Creates the Submit Button -->
                                <div class="row justify-content-end mb-3">
                                    <div class="col col-lg-4 col-sm-5 col-6 text-end d-grid gap-2 mt-4">
                                        <input type="submit" class="btn btn-primary" value="Sign-Up" onclick="validateForm(this.form);">
                                    </div>
                                </div>
                                <!-- Hyperlink to doctor sign-in page -->
                                <div class="row justify-content-end">
                                    <div class="col-12 text-end">
                                        <small>Already have an account? <a href="signInDoctors.php">Sign&hybull;In</a></small>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- Hyperlink to patient sign-up and sign-in pages -->
                <div class="container-fluid text-center">
                    <p><strong>Or</strong> do you want to enter as a <strong>patient</strong>? <a href="signUpPatients.php">Sign&hybull;Up</a>&nbsp;|&nbsp;<a href="signInPatients.php">Sign&hybull;In</a></p>
                </div>
            </div>
        </div>
    </body>
</html>
