<!--
    Generates the Sign-Up for patients page. List boxes are generated by PHP, as values are passed from the database.
-->
<?php
//Recieves any error message sent from the patient Sign-Up script. The error has to be detected on the server side.
    $outputMessage = filter_input(INPUT_GET,'outputMessage');

//Checks whether outputMessage is set, if not creates empty string variable
    if(!empty($outputMessage)){
        $outputMessage = "<p>" . $outputMessage . "</p>";
    }
    else{
        $outputMessage="";
    }

    //retrieves all recors of city table as an associative array.
    require('./database.php');  //Calls the database.php file. If an error occurs, script will terminates raising fatal error
    $query = 'select * from city;';
    $statement = $database->prepare($query);
    $statement->execute();
    $city_table = $statement->fetchAll();
    $statement->closeCursor();
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <meta name="author" content="IU Ratnayake">
        <title>Doctorr | Patient | Sign-In</title>

        <!-- Links bootstrap CSS and JavaScript to the HTML document -->
        <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
        <script src="js/bootstrap.min.js"></script>

        <!-- Links custom CSS and JavaScript to HTML document -->
        <script src="formScript.js"></script>
        <link rel="stylesheet" type="text/css" href="formStyle.css">
    </head>
    <body>
        <!-- Content alignment -->
        <div class="row my-4 align-items-center body-section">
            <div class="col">
                <!-- Heading -->
                <header>
                    <h1 class="text-center">Sign&hybull;Up&nbsp;as&nbsp;a&nbsp;Patient <img src="images/logo2.png" alt="Doctorr Logo"></h1>
                </header>
                <!-- Form alignment -->
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col col-lg-5 col-md-6 col-sm-8 col-10">
                            <!-- Patient sign-up form -->
                            <form class="container-fluid border rounded-3 pt-5 pb-4 bg-light" action="patientSignUpScript.php" method="POST">
                            <!--
                                Custom JavaScript functions are used for client side validation.
                            -->

                            <!-- prints $outputMessage -->    
                            <div class="error-msg">
                                    <div>
                                        <?php echo $outputMessage?>
                                    </div>
                                </div>
                                <!-- Name -->
                                <div class="row mb-2">
                                    <div class="col col-12">
                                        <div class="form-floating">
                                            <input type="text" id="uName" name="uName" class="form-control" placeholder="Your Name" onchange="strTrimmer(this);" onblur="invalidBorder(this);" required>
                                            <label for="uName">Name</label>
                                        </div>
                                    </div>
                                </div>
                                <!-- Gender -->
                                <div class="row mb-2 p-2 control-height align-items-center">
                                    <div class="col col-xl-2 col-sm-3 col-4">
                                        <label for="uGender">Gender</label>
                                    </div>
                                    <div class="col-xl-4 col-sm-5 col-8">
                                        <select id="uGender" name="uGender" class="form-select" onblur="invalidBorder(this);" required>
                                            <option class="select-item" value="" disabled selected></option>
                                            <option class="select-item" value="M">Male</option>
                                            <option class="select-item" value="F">Female</option>
                                        </select>
                                    </div>
                                </div>
                                <!-- Email -->
                                <div class="row mb-2">
                                    <div class="col">
                                        <div class="form-floating">
                                            <input type="email" id="uEmail" name="uEmail" class="form-control" placeholder="Your E-mail" onblur="invalidBorder(this);" required>
                                            <label for="uEmail">E-mail</label>
                                        </div>
                                    </div>
                                </div>
                                <!-- Password -->
                                <div class="row gx-2">
                                    <div class="col-xl-6 col-12">
                                        <div class="form-floating mb-2">
                                            <input type="password" id="uPassword" name="uPassword" class="form-control" minlength="8" placeholder="Your Password" onblur="invalidBorder(this);" required>
                                            <label for="uPassword">Password</label>
                                        </div>
                                    </div>
                                <!-- Confirm Password -->
                                    <div class="col-xl-6 col-12">
                                        <div class="form-floating mb-2">
                                            <input type="password" id="uPassRepeat" name="uPassRepeat" class="form-control" placeholder="Re-enter Your Password" onblur="invalidBorder(this);" oninput="clearInvalid(this);" required>
                                            <label for="uPassRepeat">Re-enter Password</label>
                                        </div>
                                    </div>
                                </div>
                                <!-- Addressline 1 -->
                                <div class="row gx-2">
                                    <div class="col-xl-6 col-12">
                                        <div class="form-floating mb-2">
                                            <input type="text" id="uAddress1" name="uAddress1" class="form-control" placeholder="Address-line 1" onchange="strTrimmer(this);" onblur="invalidBorder(this);" required>
                                            <label for="uAddress1">Addressline 1</label>
                                        </div>
                                    </div>

                                <!-- Addressline 2 -->

                                    <div class="col-xl-6 col-12">
                                        <div class="form-floating mb-2">
                                            <input type="text" id="uAddress2" name="uAddress2" class="form-control" placeholder="Address-line 2 (Optional)" onchange="strTrimmer(this);" onblur="invalidBorder(this);">
                                            <label for="uAddress2">Addressline 2 (Optional)</label>
                                        </div>
                                    </div>
                                </div>
                                <!-- City -->
                                <div class="row mb-2">
                                    <div class="col">
                                        <select id="uCity" name="uCity" class="form-select control-height" onblur="invalidBorder(this);" required>
                                            <option class="select-item" value="" disabled selected>Select Nearest City</option>
                                            <!-- Generates like of cities from table -->
                                            <?php foreach($city_table as $city_record):?>
                                                <option class="select-item" value="<?php echo $city_record['city_id']?>"><?php echo $city_record['city_name']?></option>
                                            <?php endforeach?>
                                        </select>
                                    </div>
                                </div>
                                <!-- Submit Button -->
                                <div class="row justify-content-end mb-3">
                                    <div class="col col-lg-4 col-sm-5 col-6 text-end d-grid gap-2 mt-4">
                                        <input type="submit" class="btn btn-primary" value="Sign-Up" onclick="validateForm(this.form);">
                                    </div>
                                </div>
                                <div class="row justify-content-end">
                                    <div class="col-12 text-end">
                                <!-- Hyperlink to patients sign-in page -->
                                        <small>Already have an account? <a href="signInPatients.php">Sign&hybull;In</a></small>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="container-fluid text-center">
                <!-- Hyperlink to doctor sign-up and sign-in pages -->
                    <p><strong>Or</strong> do you want to enter as a <strong>doctor</strong>? <a href="signUpDoctors.php">Sign&hybull;Up</a>&nbsp;|&nbsp;<a href="signInDoctors.php">Sign&hybull;In</a></p>
                </div>
            </div>
        </div>
    </body>
</html>
